//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIS3D.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PISEntities : DbContext
    {
        public PISEntities()
            : base("name=PISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Downspouts_Table> Downspouts_Table { get; set; }
        public virtual DbSet<EaveConditionEnum_Table> EaveConditionEnum_Table { get; set; }
        public virtual DbSet<FrameType_Table> FrameType_Table { get; set; }
        public virtual DbSet<HeightReference_Table> HeightReference_Table { get; set; }
        public virtual DbSet<LengthReference_Table> LengthReference_Table { get; set; }
        public virtual DbSet<WidthReferenceTable> WidthReferenceTables { get; set; }
        public virtual DbSet<EndWallTypeTypeTable> EndWallTypeTypeTables { get; set; }
        public virtual DbSet<WindExposureTable> WindExposureTables { get; set; }
        public virtual DbSet<ApplyLoadsPerTable> ApplyLoadsPerTables { get; set; }
        public virtual DbSet<ColdFormedDesignCodesTable> ColdFormedDesignCodesTables { get; set; }
        public virtual DbSet<DesignCodesTable> DesignCodesTables { get; set; }
        public virtual DbSet<SeismicTable> SeismicTables { get; set; }
        public virtual DbSet<WindSpeedEnumTable> WindSpeedEnumTables { get; set; }
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<PaintSystemTable> PaintSystemTables { get; set; }
        public virtual DbSet<SecondarySurfaceFinishTable> SecondarySurfaceFinishTables { get; set; }
        public virtual DbSet<SurfaceFinishTable> SurfaceFinishTables { get; set; }
        public virtual DbSet<SurfaceTreatmentTable> SurfaceTreatmentTables { get; set; }
        public virtual DbSet<BracingTypeTable> BracingTypeTables { get; set; }
    }
}
