//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIS3D.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FrameType_Table
    {
        public int ID_FrameType { get; set; }
        public string FrameType { get; set; }
    }
}
